import Head from "next/head";
import { BsMoonStarsFill } from "react-icons/bs";
import { Inter } from "@next/font/google";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";
import {
  AiFillLinkedin,
  AiFillFacebook,
  AiFillInstagram,
  AiFillGithub,
} from "react-icons/ai";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Anuj Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800">
        <section className=" min-h-screen ">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className=" text-xl dark:text-white">DEVELOPEDBY-ANUJ</h1>
            <ul className=" flex items-center ">
              <li>
                <BsMoonStarsFill
                  onClick={() => {
                    setDarkMode(!darkMode);
                  }}
                  className=" cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Anuj Shrestha
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white ">
              React Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl dark:text-white">
              I am a developer who is enthusiastic about making the web a better
              place, so I create awesome websites and web applications Hire me
              to build you a website or improve your existing one. I'm am fluent
              with React.js and its eco-system like redux for managing the state
              I can build you high performance and stable apps.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://www.linkedin.com/in/anuj-shrestha-b00113128">
              <AiFillLinkedin className="dark:text-white" />
            </a>
            <a href="https://github.com/anujsth">
              <AiFillGithub className="dark:text-white" />
            </a>
            <a href="https://www.facebook.com/anujshresth007">
              <AiFillFacebook className="dark:text-white" />
            </a>
          </div>
          <div className=" relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div className="text-center">
            <h3 className=" text-3xl py-1 pt-8 dark:text-white">
              Services I Offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Since the beginning of my journey as a developer I've developed
              various projects using languages such as HTML, CSS, Tailwind,
              Javascript and React.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              I offer from a wide range of services, that includes writing
              <span className=" text-cyan-500"> optimized codes</span>,
              developing <span className="text-cyan-500">static</span> or{" "}
              <span className="text-cyan-500">dynamic webpages</span>.
            </p>
          </div>
          <div className=" flex justify-evenly">
            <div className="shadow-lg  p-10 rounded-xl my-10 flex flex-col items-center dark:bg-white">
              <Image src={design} height={100} width={100} />
              <h3 className="pt-8 pb-2 text-lg font-medium ">
                Beautiful Designs
              </h3>
              <p className="py-2  ">
                Creating elegant designs suitable for you
              </p>
              <p className=" py-4 text-teal-500">
                Designs using tools such as :
              </p>
              <h4 className="text-grey py-1 ">Figma</h4>
              <h4 className="text-grey py-1 ">Illutrator</h4>
            </div>
            <div className="shadow-lg  p-10 rounded-xl my-10 flex flex-col items-center dark:bg-white">
              <Image src={design} height={100} width={100} />
              <h3 className="pt-8 pb-2 text-lg font-medium ">
                Beautiful Designs
              </h3>
              <p className="py-2  ">
                Creating elegant designs suitable for you
              </p>
              <p className=" py-4 text-teal-500">
                Designs using tools such as :
              </p>
              <h4 className="text-grey py-1 ">Figma</h4>
              <h4 className="text-grey py-1 ">Illutrator</h4>
            </div>
            <div className="shadow-lg  p-10 rounded-xl my-10 flex flex-col items-center dark:bg-white">
              <Image src={design} height={100} width={100} />
              <h3 className="pt-8 pb-2 text-lg font-medium ">
                Beautiful Designs
              </h3>
              <p className="py-2  ">
                Creating elegant designs suitable for you
              </p>
              <p className=" py-4 text-teal-500">
                Designs using tools such as :
              </p>
              <h4 className="text-grey py-1 ">Figma</h4>
              <h4 className="text-grey py-1 ">Illutrator</h4>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className=" text-3xl py-1 text-center dark:text-white">
              Portofolio
            </h3>
          </div>
          <div className=" flex flex-col py-10 gap-10 lg:flex-row lg:flex-wrap">
            <div className=" basis-1/3 flex-1">
              <Image
                src={web1}
                className=" rounded-lg object-cover "
                width={"100%"}
                layout="responsive"
                height={"100%"}
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web2}
                className=" rounded-lg object-cover "
                width={"100%"}
                layout="responsive"
                height={"100%"}
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web3}
                className=" rounded-lg object-cover "
                width={"100%"}
                layout="responsive"
                height={"100%"}
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web4}
                className=" rounded-lg object-cover "
                width={"100%"}
                layout="responsive"
                height={"100%"}
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web5}
                className=" rounded-lg object-cover "
                width={"100%"}
                layout="responsive"
                height={"100%"}
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={web6}
                className=" rounded-lg object-cover "
                width={"100%"}
                layout="responsive"
                height={"100%"}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
